### ISSUE TITLE
首頁的 navigation bar 的字，請對齊

### ISSUE THREAD

**Issue by shuyanglin** [JoeyChen-NTUT/advisory.yda#2]
![screenshot 2018-08-15 15 00 16](https://user-images.githubusercontent.com/4061541/44135624-760124f6-a09c-11e8-9e74-ec38d12c7234.png)
![screenshot 2018-08-15 15 00 08](https://user-images.githubusercontent.com/4061541/44136045-e189e504-a09d-11e8-9512-fbbe6271558d.png)

**Comment by Hao1995** [comment]
fixed
